name: Build Android APK (Buildozer)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system packages
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5 libncurses5-dev libffi-dev libssl-dev build-essential

    - name: Upgrade pip and install buildozer dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install cython==0.29.36
        pip install buildozer==1.5.0

    - name: (Optional) Show Python & Java versions
      run: |
        python --version
        javac -version

    - name: Build APK with Buildozer
      working-directory: ${{ github.workspace }}
      run: |
        # clean previous build (if any)
        buildozer android debug -v

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: neuroquantumai-apk
        path: bin/*.apk
