name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Pozwala na ręczne uruchomienie

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3-dev \
          python3-pip \
          libffi-dev \
          libssl-dev \
          libjpeg-dev \
          zlib1g-dev \
          libfreetype6-dev \
          libxml2-dev \
          libxslt1-dev \
          libjpeg62-turbo-dev
          
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.33
        pip install kivy[base] requests plyer pillow
        
    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: .buildozer_global
        key: buildozer-global-${{ hashFiles('buildozer.spec') }}
        
    - name: Cache Buildozer directory
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: buildozer-${{ hashFiles('buildozer.spec') }}
        
    - name: Create buildozer.spec if not exists
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
          # Dostosuj konfigurację dla Twojej aplikacji
          sed -i 's/title = My Application/title = NeuroQuantumAI/' buildozer.spec
          sed -i 's/package.name = myapp/package.name = neuroquantumai/' buildozer.spec
          sed -i 's/package.domain = org.example/package.domain = com.bagno97/' buildozer.spec
          sed -i 's/source.dir = ./source.dir = ./' buildozer.spec
          sed -i 's/version = 0.1/version = 1.0/' buildozer.spec
          sed -i 's/requirements = python3,kivy/requirements = python3,kivy,requests,plyer,pillow/' buildozer.spec
          sed -i 's/android.minapi = 21/android.minapi = 26/' buildozer.spec
          sed -i 's/android.sdk = 28/android.sdk = 34/' buildozer.spec
          sed -i 's/android.ndk = 23b/android.ndk = 25b/' buildozer.spec
          sed -i 's/#android.archs = arm64-v8a, armeabi-v7a/android.archs = arm64-v8a/' buildozer.spec
        fi
        
    - name: Build APK with Buildozer
      run: |
        buildozer android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: NeuroQuantumAI-APK
        path: bin/*.apk
        retention-days: 30
        
    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: .buildozer/android/platform/build-*/dists/*/build.log
        retention-days: 7
